#!/usr/bin/env python3
"""
Build what a sheet's Loader.gs installs: edld_sheet.js and release.json.

    edld_sheet.js   Code.gs, Dashboard.gs, Template.gs and Upgrade.gs,
                    concatenated and stamped with the version, with TEMPLATE —
                    the dashboard's content, read from build_dashboard.py — and
                    ending in the object the loader calls into. Generated;
                    never edit it.
    release.json    The version, the bundle's file name and SHA-256, the sheet
                    layout version it brings a sheet to, and the oldest loader
                    it runs under.

The manifest names the bundle by file name only, and the loader fetches it
from beside the manifest — the same branch, at the same moment. A sheet
therefore needs no tag and no GitHub Release: it follows a branch. Sheets
follow ``main`` unless their owner picks another branch from the sheet's
menu, so merging to ``main`` is what releases sheet code, and ``dev`` can be
tried in a test sheet before anything is merged or tagged.

Standard library only, so the release workflow can run ``--check`` without
installing anything. build_dashboard.py calls this too, so one run of that
writes the template, the bundle and the manifest together.

Usage:
    python3 sheets/build_bundle.py            # write both, beside this file
    python3 sheets/build_bundle.py --check    # exit 1 if either is stale
    python3 sheets/build_bundle.py [--version V] [--out-dir DIR]

--version defaults to the repository's version file.
"""

from __future__ import annotations

import argparse
import ast
import datetime as dt
import hashlib
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent

BUNDLE_NAME = 'edld_sheet.js'
MANIFEST_NAME = 'release.json'

#: Bundled into edld_sheet.js, in this order: later files use earlier ones.
BUNDLE_SOURCES = ('Code.gs', 'Dashboard.gs', 'Template.gs', 'Upgrade.gs')

#: Where the template's content is defined, once, for the xlsx and the sheet.
TEMPLATE_SOURCE = HERE / 'build_dashboard.py'


def template_content() -> dict:
    """The constants build_dashboard.py lists in TEMPLATE_KEYS, by name.

    Read from the source rather than imported, because importing it needs
    openpyxl and this must not. Each is a plain literal; anything else is a
    build error here rather than a surprise in somebody's sheet.
    """
    tree = ast.parse(TEMPLATE_SOURCE.read_text(encoding='utf-8'))
    found: dict = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        try:
            value = ast.literal_eval(node.value)
        except ValueError:
            continue
        if isinstance(target, ast.Name):
            found[target.id] = value
        elif isinstance(target, ast.Tuple) and isinstance(value, tuple):
            for elt, v in zip(target.elts, value):
                if isinstance(elt, ast.Name):
                    found[elt.id] = v
    keys = found.get('TEMPLATE_KEYS')
    if not keys:
        sys.exit('build_dashboard.py: TEMPLATE_KEYS not found')
    missing = [k for k in keys if k not in found]
    if missing:
        sys.exit(f"build_dashboard.py: TEMPLATE_KEYS names {', '.join(missing)}, "
                 f"which are not plain literals there")
    return {k: found[k] for k in keys}

#: What the bundle hands the loader. Loader.gs calls exactly these.
BUNDLE_EXPORTS = """return {
  version: EDLD_VERSION,
  doPost: doPost,
  doGet: doGet,
  onEdit: onEdit,
  onSelectionChange: onSelectionChange,
  MENU: MENU,
  upgradeSheet: upgradeSheet,
  sheetVersion: sheetVersion_,
  SHEET_VERSION: SHEET_VERSION,
  MIN_LOADER: MIN_LOADER
};
"""


def default_version() -> str:
    vf = ROOT / 'version'
    if vf.is_file():
        v = vf.read_text(encoding='utf-8').strip()
        # A bare datestamp, or one with a suffix on a development build
        # (20260926-dev), which is carried as it is.
        if re.fullmatch(r'\d{8}(?:-[A-Za-z0-9.]+)?', v):
            return v
    return dt.date.today().strftime('%Y%m%d')


def build_bundle(version: str) -> str:
    """The text Loader.gs runs, as the body of ``new Function('LOADER', …)``."""
    parts = [
        '// GENERATED by sheets/build_bundle.py from '
        + ', '.join(BUNDLE_SOURCES) + ' — do not edit.\n'
        '// Loader.gs runs this as the body of a function; see sheets/README.md.\n',
        f"var EDLD_VERSION = {version!r};\n",
        '/** The dashboard template, from build_dashboard.py. Used by Template.gs. */\n'
        'var TEMPLATE = ' + json.dumps(template_content(), ensure_ascii=False,
                                      indent=1) + ';\n',
    ]
    for name in BUNDLE_SOURCES:
        text = (HERE / name).read_text(encoding='utf-8').replace('\r\n', '\n')
        parts.append(f'\n// ── {name} ' + '─' * max(3, 70 - len(name)) + '\n\n')
        parts.append(text if text.endswith('\n') else text + '\n')
    parts.append('\n' + BUNDLE_EXPORTS)
    return ''.join(parts)


def _gs_int(path: pathlib.Path, pattern: str) -> int:
    m = re.search(pattern, path.read_text(encoding='utf-8'))
    if not m:
        sys.exit(f'{path.name}: {pattern!r} not found')
    return int(m.group(1))


def build_release(version: str, bundle_text: str) -> dict:
    """The manifest Loader.gs reads before it fetches anything else."""
    upgrade = (HERE / 'Upgrade.gs').read_text(encoding='utf-8')
    found = re.findall(r"^\s*to:\s*(\d+),\s*\n\s*name:\s*'((?:[^'\\]|\\.)*)'",
                       upgrade, re.M)
    steps = [int(n) for n, _ in found]
    if not steps or steps != sorted(steps) or len(set(steps)) != len(steps):
        sys.exit('Upgrade.gs: SHEET_MIGRATIONS must have rising, unique `to:` '
                 'versions, each followed by its name')
    data = bundle_text.encode('utf-8')
    return {
        'version': version,
        'sheet_version': steps[-1],
        # So Upgrade can say what it will do before it fetches any code.
        'sheet_steps': [{'to': int(n), 'name': name} for n, name in found],
        'min_loader': _gs_int(HERE / 'Upgrade.gs', r'var MIN_LOADER = (\d+);'),
        'bundle': {
            # Relative: fetched from beside this manifest, on the same branch.
            'file': BUNDLE_NAME,
            'sha256': hashlib.sha256(data).hexdigest(),
            'bytes': len(data),
        },
        'loader': {
            'version': _gs_int(HERE / 'Loader.gs', r'var LOADER_VERSION = (\d+);'),
            'file': 'Loader.gs',
        },
    }


def render(version: str) -> dict[str, bytes]:
    """Both files, by name, exactly as they should be on disk."""
    bundle = build_bundle(version)
    release = build_release(version, bundle)
    return {
        BUNDLE_NAME: bundle.encode('utf-8'),
        MANIFEST_NAME: (json.dumps(release, indent=2) + '\n').encode('utf-8'),
    }


def write(version: str, out_dir: pathlib.Path) -> dict:
    files = render(version)
    for name, data in files.items():
        (out_dir / name).write_bytes(data)
    return json.loads(files[MANIFEST_NAME])


def stale(version: str, out_dir: pathlib.Path) -> list[str]:
    """Names of the files that do not match a fresh build."""
    out = []
    for name, data in render(version).items():
        path = out_dir / name
        if not path.is_file() or path.read_bytes() != data:
            out.append(name)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--version', default=default_version())
    ap.add_argument('--out-dir', default=str(HERE))
    ap.add_argument('--check', action='store_true',
                    help='write nothing; exit 1 if either file is stale')
    args = ap.parse_args()
    out_dir = pathlib.Path(args.out_dir)

    if args.check:
        bad = stale(args.version, out_dir)
        if bad:
            print(f"::error::sheets/{' and sheets/'.join(bad)} "
                  f"{'is' if len(bad) == 1 else 'are'} stale for version "
                  f"{args.version}. Sheets would install code that is not the "
                  f"code in this commit. Run python3 sheets/build_bundle.py "
                  f"(or build_dashboard.py) and commit the result.")
            return 1
        print(f'sheet bundle and manifest are current for {args.version}')
        return 0

    release = write(args.version, out_dir)
    print(f"wrote {out_dir / BUNDLE_NAME} and {MANIFEST_NAME} "
          f"({args.version}, sheet layout v{release['sheet_version']})")
    return 0


if __name__ == '__main__':
    sys.exit(main())
