// GENERATED by sheets/build_bundle.py from Code.gs, Dashboard.gs, Upgrade.gs — do not edit.
// Loader.gs runs this as the body of a function; see sheets/README.md.
var EDLD_VERSION = '20260926-dev';

// ── Code.gs ───────────────────────────────────────────────────────────────

/**
 * EDLD surface survey — Google Sheets receiver.
 *
 * Deploy this bound to the spreadsheet you want deposits written to. EDLD
 * POSTs batches of deposits here; this script decides what is new, what has
 * changed, and what to ignore.
 *
 * Not pasted into a sheet on its own any more. This file, Dashboard.gs and
 * Upgrade.gs are bundled by build_dashboard.py into edld_sheet.js, which
 * Loader.gs — the one file a sheet owner pastes — installs and upgrades from
 * the sheet's own menu. Setup is in sheets/README.md.
 *
 * Why the dedupe lives here rather than in EDLD
 * ---------------------------------------------
 * A squadron sheet has several commanders writing to it, and none of them can
 * see the others' local stores. Only the sheet knows what is already in the
 * sheet. Put the check on the client and two commanders who find the same
 * deposit in the same evening both append it, because each was right about
 * what it had seen. Here, LockService serialises them and the second one
 * updates the first one's row.
 *
 * Matching is exact string equality on deposit_id. EDLD works out the geometry
 * — same system, same body, same commodity, within 75 m — and hands over a
 * stable id. This script never needs to know a deposit has moved a few metres.
 */

// ── Configuration ────────────────────────────────────────────────────────────

/**
 * Shared secret. EDLD sends it as "Authorization: Bearer <token>"; Apps Script
 * strips that header from web app requests, so it is re-sent in the body too
 * and read from there.
 *
 * It lives in the script's properties, set from the sheet with ED Dashboard >
 * Set sheet token, not in this file. An upgrade replaces this file, and a
 * token written into it would be replaced along with it — every commander's
 * configured token would stop working at once. Change it to revoke access:
 * anyone holding the old one stops being able to write, and the URL does not
 * have to change.
 */
var TOKEN_PROPERTY = 'EDLD_TOKEN';

function _token() {
  return String(PropertiesService.getScriptProperties()
                  .getProperty(TOKEN_PROPERTY) || '');
}

/** Sheet tab that deposits are written to. Created if absent. */
var SHEET_NAME = 'Deposits';

/**
 * Column order. This is a contract with core/sheets_publish.py — the client
 * sends objects, this array decides where each value lands, so adding a field
 * means appending here and in the client's COLUMNS. Never reorder: existing
 * rows are positional.
 */
var COLUMNS = [
  'deposit_id',
  'system',
  'system_address',
  'body',
  'body_id',
  'planet_class',
  'gravity',
  'body_radius_m',
  'atmosphere',
  'volcanism',
  'signal_no',
  'commodity',
  'latitude',
  'longitude',
  'density_claimed',
  'density_observed',
  'amount',
  'rigs',
  'refine_count',
  'first_seen',
  'last_confirmed',
  'reported_by',
  'is_test',
  'depleted_on',
  'notes',
  'notes_updated',
  'assessment_updated'
];

/**
 * Fields a later report is allowed to overwrite on an existing row.
 *
 * notes is not here. It is a commander's writing rather than an observation,
 * so a newer sighting of the site says nothing about whether the note is
 * current; it has its own timestamp, notes_updated, and _update() lets the
 * newer of those win outright — even when the newer note is blank, because
 * that is how its author withdraws it.
 */
var MUTABLE = [
  'rigs', 'refine_count',
  'last_confirmed', 'signal_no', 'planet_class', 'gravity', 'body_radius_m',
  'atmosphere', 'volcanism', 'system', 'body'
];

/**
 * Assessments: what the HUD said the site holds. A later report fills them
 * only where they are blank. They are replaced only by a correction — a
 * report whose assessment_updated is newer than the row's — so a commander
 * who merely drives onto a site cannot put back a value somebody fixed.
 *
 * Nothing here is ever "Depleted". A worked-out site is recorded by its
 * depleted_on date alone, and the latest date wins; older sheets that wrote
 * the word into amount have it cleared the next time the row is touched.
 */
var ASSESSED = ['amount', 'density_observed', 'density_claimed'];

// ── Entry points ─────────────────────────────────────────────────────────────

function doPost(e) {
  try {
    var body = JSON.parse((e && e.postData && e.postData.contents) || '{}');

    var token = _token();
    if (!token) {
      return _json({ ok: false, error: 'server token not configured — in the ' +
                     'sheet, run ED Dashboard > Set sheet token' });
    }
    if (String(body.token || '') !== token) {
      return _json({ ok: false, error: 'bad token' });
    }

    if (body.ping) {
      // What is installed, so EDLD's Test connection can say which side is
      // behind rather than only that something is.
      return _json({
        ok: true, pong: true, columns: COLUMNS.length,
        version: typeof EDLD_VERSION === 'undefined' ? '' : EDLD_VERSION,
        sheet_version: Number(PropertiesService.getDocumentProperties()
                                .getProperty('EDLD_SHEET_VERSION') || 0)
      });
    }

    // Read: everything this sheet knows about one body.
    //
    // The write half alone made the survey a place to send data and never a
    // place to get any, which left the in-game compass pointing only at
    // deposits the commander had already found — something the game's own HUD
    // already shows them. The point of a shared sheet is the deposits somebody
    // else found.
    if (body.fetch) {
      return _json(_read(body.fetch));
    }

    // Removal. EDLD only ever asks for this when the commander is standing at
    // the deposit, which is the closest thing to proof that they know what
    // they are removing.
    if (body.delete) {
      return _json(_remove(body.delete));
    }

    var deposits = body.deposits;
    if (!deposits || !deposits.length) {
      return _json({ ok: true, added: 0, updated: 0, unchanged: 0 });
    }

    return _json(_write(deposits));
  } catch (err) {
    // Returned rather than thrown: a thrown error becomes an HTML error page
    // that the client cannot parse, so the failure would reach EDLD as
    // "unreadable response" instead of as what actually went wrong.
    return _json({ ok: false, error: String(err) });
  }
}

function doGet() {
  return _json({ ok: true, service: 'EDLD surface survey', columns: COLUMNS.length });
}

// ── Writing ──────────────────────────────────────────────────────────────────

function _read(query) {
  var sheet = _sheet();
  var lastRow = sheet.getLastRow();
  if (lastRow < 2) return { ok: true, deposits: [] };

  var sysCol = COLUMNS.indexOf('system_address');
  var bodyCol = COLUMNS.indexOf('body_id');
  var testCol = COLUMNS.indexOf('is_test');

  var wantSys = String(query.system_address || '');
  var wantBody = String(query.body_id || '');
  if (!wantSys || !wantBody) return { ok: false, error: 'system_address and body_id required' };

  // One read of the whole range, then filter here. A getRange per row is the
  // difference between this answering instantly and timing out once the sheet
  // has a few thousand rows in it.
  var values = sheet.getRange(2, 1, lastRow - 1, COLUMNS.length).getValues();
  var out = [];
  for (var i = 0; i < values.length; i++) {
    var row = values[i];
    if (String(row[sysCol]) !== wantSys) continue;
    if (String(row[bodyCol]) !== wantBody) continue;
    if (testCol >= 0 && String(row[testCol]) === '1') continue;
    var dep = {};
    for (var c = 0; c < COLUMNS.length; c++) dep[COLUMNS[c]] = row[c];
    // As EDLD would have sent them: a day rather than whatever Sheets made of
    // a date it parsed, and no amount of "Depleted" from an older sheet.
    dep.depleted_on = _day(dep.depleted_on);
    if (String(dep.amount) === 'Depleted') dep.amount = '';
    out.push(dep);
  }
  return { ok: true, deposits: out };
}


function _remove(query) {
  var lock = LockService.getDocumentLock();
  if (!lock.tryLock(30000)) return { ok: false, error: 'sheet busy, try again' };
  try {
    var id = String(query.deposit_id || '').trim();
    if (!id) return { ok: false, error: 'deposit_id required' };
    var sheet = _sheet();
    var lastRow = sheet.getLastRow();
    if (lastRow < 2) return { ok: true, added: 0, updated: 0, unchanged: 0 };

    var ids = sheet.getRange(2, 1, lastRow - 1, 1).getValues();
    for (var i = ids.length - 1; i >= 0; i--) {
      if (String(ids[i][0] || '').trim() === id) {
        sheet.deleteRow(i + 2);
        return { ok: true, added: 0, updated: 1, unchanged: 0 };
      }
    }
    return { ok: true, added: 0, updated: 0, unchanged: 0 };
  } finally {
    lock.releaseLock();
  }
}


function _write(deposits) {
  // Thirty seconds is long enough for a batch and short enough that a stuck
  // lock surfaces as an error rather than a hang.
  var lock = LockService.getDocumentLock();
  if (!lock.tryLock(30000)) {
    return { ok: false, error: 'sheet busy, try again' };
  }
  try {
    var sheet = _sheet();
    var lastRow = sheet.getLastRow();
    var added = 0, updated = 0, unchanged = 0;

    // Row index by deposit_id, read once. Column A only — pulling the whole
    // sheet to find one column is the difference between this finishing and
    // this timing out once the sheet has a few thousand rows in it.
    var index = {};
    if (lastRow > 1) {
      var ids = sheet.getRange(2, 1, lastRow - 1, 1).getValues();
      for (var i = 0; i < ids.length; i++) {
        var id = String(ids[i][0] || '').trim();
        if (id) index[id] = i + 2;
      }
    }

    var appends = [];
    for (var d = 0; d < deposits.length; d++) {
      var dep = deposits[d];
      var depId = String(dep.deposit_id || '').trim();
      if (!depId) continue;

      var row = index[depId];
      if (!row) {
        appends.push(_toRow(dep));
        // Guard against the same id appearing twice inside one batch.
        index[depId] = -1;
        added++;
        continue;
      }
      if (row < 0) continue;  // already queued for append in this batch

      if (_update(sheet, row, dep)) updated++; else unchanged++;
    }

    if (appends.length) {
      sheet.getRange(sheet.getLastRow() + 1, 1, appends.length, COLUMNS.length)
           .setValues(appends);
    }
    return { ok: true, added: added, updated: updated, unchanged: unchanged };
  } finally {
    lock.releaseLock();
  }
}

function _update(sheet, row, dep) {
  var current = sheet.getRange(row, 1, 1, COLUMNS.length).getValues()[0];
  var changed = false;

  for (var m = 0; m < MUTABLE.length; m++) {
    var field = MUTABLE[m];
    var col = COLUMNS.indexOf(field);
    if (col < 0) continue;
    if (!(field in dep)) continue;

    var incoming = dep[field];
    if (incoming === null || incoming === undefined || incoming === '') continue;

    // A blank stored value is always filled in. A populated one is only
    // replaced when the report is newer than what is on the row, so a
    // commander replaying an old session cannot walk back a fresher reading.
    var existing = current[col];
    if (String(existing) === String(incoming)) continue;
    if (existing !== '' && existing !== null && !_isNewer(dep, current)) continue;

    sheet.getRange(row, col + 1).setValue(_cell(incoming));
    current[col] = incoming;
    changed = true;
  }

  // Assessments: fill blanks; replace only on a newer correction.
  var aCol = COLUMNS.indexOf('assessment_updated');
  var aStamp = String(dep.assessment_updated || '');
  var corrected = aCol >= 0 && aStamp !== '' &&
                  aStamp > String(current[aCol] || '');
  for (var a = 0; a < ASSESSED.length; a++) {
    var aField = ASSESSED[a];
    var ac = COLUMNS.indexOf(aField);
    var held = String(current[ac] === null ? '' : current[ac]);
    var legacy = held === 'Depleted';
    var sent = (aField in dep && dep[aField] !== null && dep[aField] !== undefined)
               ? String(dep[aField]) : '';
    if (sent === '') {
      if (legacy) { sheet.getRange(row, ac + 1).setValue(''); current[ac] = ''; changed = true; }
      continue;
    }
    if (sent === held) continue;
    if (held !== '' && !legacy && !corrected) continue;
    sheet.getRange(row, ac + 1).setValue(_cell(sent));
    current[ac] = sent;
    changed = true;
  }
  if (corrected) {
    sheet.getRange(row, aCol + 1).setValue(aStamp);
    current[aCol] = aStamp;
    changed = true;
  }

  // Depletion: the latest date wins. Sites refill and are worked out again,
  // so the most recent emptying is the one that describes the site now.
  var dCol = COLUMNS.indexOf('depleted_on');
  var day = _day(dep.depleted_on);
  if (dCol >= 0 && day && day > _day(current[dCol])) {
    sheet.getRange(row, dCol + 1).setValue("'" + day);
    current[dCol] = day;
    changed = true;
  }

  // Notes: last writer wins, by notes_updated. Equal stamps are the same note
  // coming back round; an older one is somebody re-sending a copy they
  // imported before its author changed it.
  var noteCol = COLUMNS.indexOf('notes');
  var stampCol = COLUMNS.indexOf('notes_updated');
  var stamp = String(dep.notes_updated || '');
  if (noteCol >= 0 && stampCol >= 0 && stamp &&
      stamp > String(current[stampCol] || '')) {
    var note = String(dep.notes || '');
    if (String(current[noteCol] || '') !== note) {
      sheet.getRange(row, noteCol + 1).setValue(_cell(note));
      current[noteCol] = note;
    }
    sheet.getRange(row, stampCol + 1).setValue(stamp);
    current[stampCol] = stamp;
    changed = true;
  }
  return changed;
}

function _isNewer(dep, currentRow) {
  var col = COLUMNS.indexOf('last_confirmed');
  if (col < 0) return true;
  var theirs = String(dep.last_confirmed || '');
  var ours = String(currentRow[col] || '');
  if (!ours) return true;
  return theirs >= ours;
}

function _toRow(dep) {
  var row = [];
  for (var c = 0; c < COLUMNS.length; c++) {
    var v = dep[COLUMNS[c]];
    if (v === null || v === undefined) v = '';
    // A bare day is text, not a date: Sheets would otherwise parse it into
    // its own timezone and hand back something else on the next read.
    else if (COLUMNS[c] === 'depleted_on' && v !== '') v = "'" + _day(v);
    else v = _cell(v);
    row.push(v);
  }
  return row;
}

/** A depletion date as YYYY-MM-DD, from text or from a date Sheets parsed. */
function _day(v) {
  if (v === null || v === undefined || v === '') return '';
  if (Object.prototype.toString.call(v) === '[object Date]') {
    return Utilities.formatDate(v, Session.getScriptTimeZone(), 'yyyy-MM-dd');
  }
  return String(v).slice(0, 10);
}

/**
 * A value as it should be written to a cell.
 *
 * Sheets reads a string starting with = + - or @ as a formula, and notes are
 * free text from anyone holding the token. Unescaped, "=IMPORTXML(...)" in a
 * note would run in every reader's copy of the sheet. A leading apostrophe
 * makes Sheets store the text as typed; it is not part of the value, so
 * getValues() — and so _read() — returns the note exactly as it was sent.
 * A string that itself starts with an apostrophe gets a second one, or Sheets
 * would take the first as that marker and drop it. Numbers arrive as numbers
 * and are left alone.
 */
function _cell(v) {
  if (typeof v === 'string' && /^[=+\-@']/.test(v)) return "'" + v;
  return v;
}

function _sheet() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName(SHEET_NAME);
  if (!sheet) sheet = ss.insertSheet(SHEET_NAME);

  // A sheet created before a column was added keeps its old header, and the
  // header is only written when the sheet is empty — so an existing squadron
  // sheet would have silently dropped every value past its last column. Widen
  // it in place instead. Columns are only ever appended, never reordered, so
  // the existing data stays where it is.
  var have = sheet.getLastColumn();
  if (have > 0 && have < COLUMNS.length) {
    sheet.getRange(1, have + 1, 1, COLUMNS.length - have)
         .setValues([COLUMNS.slice(have)])
         .setFontWeight('bold');
  }

  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, COLUMNS.length).setValues([COLUMNS]);
    sheet.setFrozenRows(1);
    sheet.getRange(1, 1, 1, COLUMNS.length).setFontWeight('bold');
    // Latitude and longitude need the decimal places. Sheets rounds them for
    // display by default, which makes a coordinate look wrong when copied out
    // even though the stored value is fine.
    var latCol = COLUMNS.indexOf('latitude') + 1;
    sheet.getRange(2, latCol, sheet.getMaxRows() - 1, 2).setNumberFormat('0.000000');
  }
  return sheet;
}

function _json(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj))
                       .setMimeType(ContentService.MimeType.JSON);
}

// ── Dashboard.gs ──────────────────────────────────────────────────────────

/**
 * EDLD mining dashboard — theme, header sorting, and formula repair.
 *
 * Bundled with Code.gs and Upgrade.gs into edld_sheet.js, which Loader.gs
 * installs and runs; nobody pastes this file. The menu is built by the loader
 * from MENU below, so an upgrade can change what the menu offers.
 *
 * What it does
 * ------------
 * Theme.   Sheets cannot colour a cell from a formula, so the hex codes on the
 *          Settings tab are only numbers until something applies them. This does,
 *          on every edit to Settings!B5:B21 or the Themes tab, and from the menu.
 *
 * Sorting. The dashboard table is a single FILTER formula, and Range.sort()
 *          cannot reorder a formula's output. Sorting is therefore done inside
 *          the formula, driven by the Sort By / Order cells (Dashboard!E5:F5).
 *          Those dropdowns work with no script at all. This adds click-to-sort:
 *          click a header to sort by it, click it again to reverse.
 *
 * Repair.  The xlsx template carries its Sheets-only formulas in the wrapper
 *          Google itself uses for export, and Sheets restores them on import.
 *          If that ever fails, ED Dashboard > Repair dashboard formulas rewrites
 *          them from FORMULAS below. build_dashboard.py reads FORMULAS from this
 *          file, so this is the one place they are defined.
 *
 *          It also lays the table out for the current column set, which is
 *          why Upgrade.gs runs the same code: a sheet from an older template
 *          comes out the same as a fresh one, without re-importing anything.
 */

const ED = {
  SETTINGS: 'Settings',
  DASH: 'Dashboard',
  THEMES: 'Themes',
  QUERIES: 'Queries',
  THEME_CELL: 'B5',
  TITLE_FONT_CELL: 'B6',
  BODY_FONT_CELL: 'B7',
  ROLE_FIRST_ROW: 10,     // Settings!A10:A21 hold the role names
  ROLE_COUNT: 12,
  NOTES_ROW: 24,
  NOTES_LINES: 5,
  HEADER_ROW: 7,          // Dashboard row the table header lands on
  DATA_FIRST_ROW: 8,
  DATA_COLS: 10,          // A:J
  DASH_COLS: 11,          // A:K (K is a margin)
  NOTES_COL: 10,          // J, the one column of prose
  SORT_BY_CELL: 'E5',
  SORT_ORDER_CELL: 'F5',
  SORT_NAMES: 'D1:M1',    // Queries: plain header names, the Sort By list
  PARK_CELL: 'K7',        // where selection goes after a header click
  // The table's columns, in the order the FILTER below emits them. Must match
  // HEADERS in build_dashboard.py; tests/test_sheets_dashboard.py checks.
  HEADERS: ['System', 'Body', 'Gravity', 'Mining Site', 'Commodity',
            'Amount', 'Density', 'Rigs', 'Depleted', 'Notes'],
  // Column widths in pixels, A:K, for Repair to lay an older sheet out with.
  WIDTHS: [130, 160, 80, 100, 170, 95, 80, 60, 100, 280, 20],
  FALLBACK: {             // Classic HUD, used when a cell is blank or not #RRGGBB
    'Background': '#0A0A0A', 'Panel': '#16100A', 'Panel Alt': '#2B1E0E',
    'Accent': '#FF7100', 'Accent Text': '#0A0A0A', 'Title': '#FF8C1A',
    'Text': '#FFB266', 'Text Dim': '#9A5A1E', 'Border': '#4A2800',
    'Highlight': '#FFD24A', 'Warning': '#E0301E', 'Input Text': '#FFA040'
  }
};
const HEX = /^#[0-9a-f]{6}$/i;

/**
 * Sheets-only formulas. Keep each one a plain template literal with no ${}:
 * build_dashboard.py parses them out of this file by regex.
 *
 * The FILTER picks Deposits columns by letter, so it depends on COLUMNS in
 * Code.gs; tests/test_sheets_dashboard.py checks each letter against it. The
 * rank list in the SORT is AMOUNT_LEVELS from core/mining_db.py, lowest first,
 * and is checked too.
 */
const FORMULAS = {
  'Dashboard!A7': `=IF(
  AND(Dashboard!$A$5="", Dashboard!$B$5=""),
  "",
  {
    Queries!$D$2:$M$2;
    IFERROR(
      LET(
        dep, FILTER(
          {Deposits!B2:B, Deposits!D2:D, Deposits!G2:G, Deposits!K2:K, Deposits!L2:L,
           Deposits!Q2:Q, Deposits!P2:P, Deposits!R2:R, Deposits!X2:X, Deposits!Y2:Y},
          (Dashboard!$A$5="") + (Deposits!B2:B=Dashboard!$A$5) > 0,
          (Dashboard!$B$5="") + (Deposits!L2:L=Dashboard!$B$5) > 0,
          Deposits!W2:W <> 1
        ),
        sortkey, INDEX(dep, 0, Queries!$N$1),
        SORT(
          dep,
          ARRAYFORMULA(IFERROR(MATCH(sortkey, {"Low";"Medium";"High"}, 0), sortkey)),
          Queries!$N$2
        )
      ),
      {"No deposits match this filter","","","","","","","","",""}
    )
  }
)`,
  'Queries!A1': `=IFERROR(SORT(UNIQUE(FILTER(Deposits!B2:B, Deposits!B2:B<>"", Deposits!W2:W<>1))), "")`,
  'Queries!B1': `=IFERROR(SORT(UNIQUE(FILTER(Deposits!L2:L, Deposits!L2:L<>"", Deposits!W2:W<>1))), "")`
};

// ------------------------------------------------------------------ triggers & menu

/**
 * The menu's own items, above the loader's Upgrade / Set sheet token / About.
 * Loader.gs maps each to a fixed dispatcher, so this list can change in an
 * upgrade without the pasted loader changing.
 */
const MENU = [
  { label: 'Apply theme', run: () => applyTheme() },
  { label: 'Copy active theme to Custom', run: () => copyActiveToCustom() },
  { label: 'Repair dashboard formulas', run: () => repairFormulas() },
];

function onEdit(e) {
  if (!e || !e.range) return;
  const name = e.range.getSheet().getName();
  if (name === ED.THEMES) { applyTheme(); return; }
  if (name !== ED.SETTINGS) return;
  const lastRoleRow = ED.ROLE_FIRST_ROW + ED.ROLE_COUNT - 1;
  const touchesCol = e.range.getColumn() <= 2 && e.range.getLastColumn() >= 2;
  const touchesRows = e.range.getLastRow() >= 5 && e.range.getRow() <= lastRoleRow;
  if (touchesCol && touchesRows) applyTheme();
}

/**
 * Click-to-sort. A click on a header cell sets Sort By to that column, or flips
 * Order if it already is, then moves the selection off the header so the next
 * click on the same header fires again. Viewers without edit access can still
 * use the table; their clicks just do nothing.
 */
function onSelectionChange(e) {
  const r = e && e.range;
  if (!r || r.getNumRows() !== 1 || r.getNumColumns() !== 1) return;
  if (r.getRow() !== ED.HEADER_ROW || r.getColumn() > ED.DATA_COLS) return;
  const sh = r.getSheet();
  if (sh.getName() !== ED.DASH) return;
  if (sh.getRange(ED.HEADER_ROW, 1).getDisplayValue() === '') return;  // no table yet

  const names = sh.getParent().getSheetByName(ED.QUERIES)
    .getRange(ED.SORT_NAMES).getDisplayValues()[0];
  const name = names[r.getColumn() - 1];
  if (!name) return;

  const by = sh.getRange(ED.SORT_BY_CELL);
  const order = sh.getRange(ED.SORT_ORDER_CELL);
  if (by.getDisplayValue() === name) {
    order.setValue(order.getDisplayValue() === 'Descending' ? 'Ascending' : 'Descending');
  } else {
    by.setValue(name);
    order.setValue('Ascending');
  }
  sh.getRange(ED.PARK_CELL).activate();
}

// ------------------------------------------------------------------ public actions

function applyTheme() {
  const ss = SpreadsheetApp.getActive();
  if (!ss.getSheetByName(ED.SETTINGS)) return;   // a receiver-only sheet
  const t = readTheme_(ss);
  const dash = ss.getSheetByName(ED.DASH);
  const set = ss.getSheetByName(ED.SETTINGS);
  const thm = ss.getSheetByName(ED.THEMES);
  if (dash) styleDashboard_(dash, t);
  if (set) styleSettings_(set, t);
  if (thm) styleThemes_(thm, t);
}

/** Copies the currently active colours into the Custom column and switches Theme to Custom. */
function copyActiveToCustom() {
  const ss = SpreadsheetApp.getActive();
  const st = ss.getSheetByName(ED.SETTINGS);
  const t = readTheme_(ss);
  st.getRange(ED.ROLE_FIRST_ROW, 2, ED.ROLE_COUNT, 1)
    .setValues(t.roles.map(r => [t.c[r]]));
  st.getRange(ED.THEME_CELL).setValue('Custom');
  applyTheme(); // programmatic edits don't fire onEdit
}

/**
 * Rewrites the Sheets-only formulas, clearing each one's spill area first, and
 * brings the table's helpers and layout up to the current column set: the
 * header names and sort arrows on Queries, the Sort By list, column widths,
 * and wrapping on the Notes column. A sheet from an older template comes out
 * the same as a fresh one.
 */
function repairFormulas() {
  const ss = SpreadsheetApp.getActive();
  if (!rebuildDashboard_(ss)) {
    ss.toast('This sheet has no Dashboard and Queries tabs to repair.', 'ED Dashboard');
    return;
  }
  tidyDeposits_(ss);
  applyTheme();
  ss.toast('Dashboard formulas and layout rewritten.', 'ED Dashboard');
}

/** Everything Repair does to the Dashboard and Queries tabs. False if absent. */
function rebuildDashboard_(ss) {
  const dash = ss.getSheetByName(ED.DASH);
  const q = ss.getSheetByName(ED.QUERIES);
  if (!dash || !q) return false;
  const H = ED.HEADERS, n = H.length;

  // Room for the layout below, on a sheet somebody has trimmed.
  if (dash.getMaxColumns() < ED.DASH_COLS)
    dash.insertColumnsAfter(dash.getMaxColumns(), ED.DASH_COLS - dash.getMaxColumns());
  if (q.getMaxColumns() < 15)
    q.insertColumnsAfter(q.getMaxColumns(), 15 - q.getMaxColumns());

  // Everything the older layout wrote, one column wider for the margin.
  dash.getRange(ED.HEADER_ROW, 1, dash.getMaxRows() - ED.HEADER_ROW + 1, ED.DASH_COLS).clearContent();
  q.getRange(1, 1, q.getMaxRows(), q.getMaxColumns()).clearContent();

  // Queries helpers: names (the Sort By list), names with the sort arrow (the
  // table header), the sort column index and direction.
  q.getRange(1, 4, 1, n).setValues([H]);
  const arrows = H.map((_, i) => {
    const c = String.fromCharCode(68 + i);     // D, E, ...
    return `=${c}1&IF(${c}1=Dashboard!$E$5,IF(Dashboard!$F$5="Descending"," ▼"," ▲"),"")`;
  });
  q.getRange(2, 4, 1, n).setFormulas([arrows]);
  const last = String.fromCharCode(68 + n - 1);
  q.getRange('N1').setFormula(`=IFERROR(MATCH(Dashboard!$E$5,$D$1:$${last}$1,0),1)`);
  q.getRange('N2').setFormula('=Dashboard!$F$5<>"Descending"');
  q.getRange('O1:O2').setValues([['← sort column index'], ['← ascending?']]);

  Object.keys(FORMULAS).forEach(key => {
    const [sheet, a1] = key.split('!');
    ss.getSheetByName(sheet).getRange(a1).setFormula(FORMULAS[key]);
  });

  dash.getRange(ED.SORT_BY_CELL).setDataValidation(
    SpreadsheetApp.newDataValidation()
      .requireValueInRange(q.getRange(ED.SORT_NAMES), true).build());

  // Layout: widths across A:K, the margin column shown, everything past it
  // hidden, and the Notes column wrapped so a long note reads as a paragraph.
  ED.WIDTHS.forEach((w, i) => dash.setColumnWidth(i + 1, w));
  dash.showColumns(1, ED.DASH_COLS);
  const maxC = dash.getMaxColumns();
  if (maxC > ED.DASH_COLS) dash.hideColumns(ED.DASH_COLS + 1, maxC - ED.DASH_COLS);
  const dataRows = dash.getMaxRows() - ED.DATA_FIRST_ROW + 1;
  dash.getRange(ED.DATA_FIRST_ROW, 1, dataRows, ED.DATA_COLS).setVerticalAlignment('top');
  dash.getRange(ED.HEADER_ROW, ED.NOTES_COL, dataRows + 1, 1)
    .setWrap(true).setHorizontalAlignment('left');
  return true;
}

// ------------------------------------------------------------------ theme resolution

function readTheme_(ss) {
  const st = ss.getSheetByName(ED.SETTINGS);
  const th = ss.getSheetByName(ED.THEMES);
  const R0 = ED.ROLE_FIRST_ROW, N = ED.ROLE_COUNT;

  const roles = st.getRange(R0, 1, N, 1).getDisplayValues().map(r => r[0].trim());
  const custom = st.getRange(R0, 2, N, 1).getDisplayValues().map(r => r[0].trim());
  const name = st.getRange(ED.THEME_CELL).getDisplayValue().trim();

  // Resolve from the Themes tab directly rather than Settings!D, so the result
  // never depends on whether the Active column has recalculated yet.
  let source = custom;
  if (name && name.toLowerCase() !== 'custom' && th) {
    const data = th.getDataRange().getDisplayValues();
    const col = data[0].map(s => s.trim()).indexOf(name);
    if (col > 0) {
      const byRole = {};
      data.slice(1).forEach(row => { byRole[row[0].trim()] = (row[col] || '').trim(); });
      source = roles.map(r => byRole[r] || '');
    }
  }

  const c = {};
  Object.keys(ED.FALLBACK).forEach(role => {
    const i = roles.indexOf(role);
    let v = i >= 0 ? source[i] : '';
    if (!HEX.test(v)) v = (i >= 0 && HEX.test(custom[i])) ? custom[i] : ED.FALLBACK[role];
    c[role] = v.toUpperCase();
  });

  return {
    c: c,
    roles: roles,
    custom: custom,
    titleFont: st.getRange(ED.TITLE_FONT_CELL).getDisplayValue().trim() || 'Orbitron',
    bodyFont: st.getRange(ED.BODY_FONT_CELL).getDisplayValue().trim() || 'Exo 2'
  };
}

function contrast_(hex) {
  const n = parseInt(hex.slice(1), 16);
  const r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
  return (0.299 * r + 0.587 * g + 0.114 * b) > 140 ? '#000000' : '#FFFFFF';
}

// ------------------------------------------------------------------ Dashboard

function styleDashboard_(sh, t) {
  const c = t.c, D = ED.DATA_COLS, maxR = sh.getMaxRows();
  const SOLID = SpreadsheetApp.BorderStyle.SOLID;
  sh.setHiddenGridlines(true);
  sh.setTabColor(c['Accent']);

  // Base layer
  sh.getRange(1, 1, maxR, ED.DASH_COLS)
    .setBackground(c['Background'])
    .setFontColor(c['Text'])
    .setFontFamily(t.bodyFont)
    .setFontSize(10)
    .setFontWeight('normal')
    .setFontStyle('normal')
    .setBorder(false, false, false, false, false, false);

  // Title block
  sh.getRange('A1').setFontFamily(t.titleFont).setFontSize(20)
    .setFontWeight('bold').setFontColor(c['Title']);
  sh.getRange('A2').setFontColor(c['Text Dim']).setFontStyle('italic');
  sh.getRange('E2').setFontColor(c['Text Dim']).setFontSize(9);
  sh.getRange(3, 1, 1, D).setBackground(c['Accent']);           // HUD stripe

  // Filter and sort controls
  sh.getRangeList(['A4:B4', 'E4:F4']).setFontColor(c['Text Dim'])
    .setFontWeight('bold').setFontSize(9);
  sh.getRangeList(['A5:B5', 'E5:F5']).setBackground(c['Panel'])
    .setFontColor(c['Input Text']).setFontWeight('bold')
    .setBorder(true, true, true, true, true, false, c['Accent'], SOLID);

  // Conditional formatting, rebuilt every time. Sheets applies the first rule
  // that matches, so the specific rules go before the general ones — and every
  // pair that could overlap is also written to be mutually exclusive, so order
  // only matters between High/Low and the plain banding.
  const r0 = ED.DATA_FIRST_ROW, n = maxR - r0 + 1;
  const header = sh.getRange(ED.HEADER_ROW, 1, 1, D);
  const all = sh.getRange(r0, 1, n, D);
  const hilo = sh.getRange(r0, 6, n, 2);                          // Amount, Density
  const bands = [[0, c['Panel']], [1, c['Panel Alt']]];           // row 8 is even
  const mk = (range, formula, bg, fg, o) => {
    let b = SpreadsheetApp.newConditionalFormatRule()
      .whenFormulaSatisfied(formula).setRanges([range])
      .setBackground(bg).setFontColor(fg);
    if (o && o.bold) b = b.setBold(true);
    if (o && o.italic) b = b.setItalic(true);
    if (o && o.strike) b = b.setStrikethrough(true);
    return b.build();
  };
  const rules = [];
  const h = ED.HEADER_ROW;
  rules.push(mk(header, `=$A$${h}<>""`, c['Accent'], c['Accent Text'], { bold: true }));
  bands.forEach(([p, bg]) => {
    rules.push(mk(hilo, `=AND($A${r0}<>"",$I${r0}="",F${r0}="High",MOD(ROW(),2)=${p})`,
      bg, c['Highlight'], { bold: true }));
    rules.push(mk(hilo, `=AND($A${r0}<>"",$I${r0}="",F${r0}="Low",MOD(ROW(),2)=${p})`,
      bg, c['Text Dim']));
  });
  bands.forEach(([p, bg]) => rules.push(mk(all,
    `=AND($A${r0}<>"",$I${r0}<>"",MOD(ROW(),2)=${p})`, bg, c['Warning'], { italic: true, strike: true })));
  bands.forEach(([p, bg]) => rules.push(mk(all,
    `=AND($A${r0}<>"",$I${r0}="",MOD(ROW(),2)=${p})`, bg, c['Text'])));
  sh.setConditionalFormatRules(rules);   // replaces all CF rules on Dashboard
}

// ------------------------------------------------------------------ Settings

function styleSettings_(sh, t) {
  const c = t.c, R0 = ED.ROLE_FIRST_ROW, N = ED.ROLE_COUNT;
  const SOLID = SpreadsheetApp.BorderStyle.SOLID;
  const maxR = Math.max(sh.getLastRow() + 5, 40);
  sh.setHiddenGridlines(true);
  sh.setTabColor(c['Text Dim']);

  sh.getRange(1, 1, maxR, 8).setBackground(c['Background']).setFontColor(c['Text'])
    .setFontFamily(t.bodyFont).setFontWeight('normal').setFontStyle('normal')
    .setBorder(false, false, false, false, false, false);

  sh.getRangeList(['A1:A2', 'A5:A7']).setFontColor(c['Text Dim']).setFontWeight('bold');
  sh.getRangeList(['B1:B2', 'B5:B7']).setBackground(c['Panel'])
    .setFontColor(c['Input Text']).setFontWeight('bold')
    .setBorder(null, null, true, null, null, null, c['Accent'], SOLID);
  sh.getRange('D1').setFontColor(c['Text Dim']).setFontSize(9);
  sh.getRange('C5:C6').setFontColor(c['Text Dim']).setFontStyle('italic').setFontSize(9);
  sh.getRange('A4').setFontFamily(t.titleFont).setFontColor(c['Title'])
    .setFontWeight('bold').setFontSize(12);

  // Colour table
  sh.getRange(R0 - 1, 1, 1, 6).setBackground(c['Accent'])
    .setFontColor(c['Accent Text']).setFontWeight('bold');
  const bgs = [];
  for (let i = 0; i < N; i++) {
    const band = i % 2 ? c['Panel Alt'] : c['Panel'];
    const cust = HEX.test(t.custom[i]) ? t.custom[i] : c['Background'];
    const active = c[t.roles[i]] || c['Background'];
    bgs.push([band, band, cust, band, active, band]);
  }
  sh.getRange(R0, 1, N, 6).setBackgrounds(bgs)
    .setBorder(null, null, null, null, null, true, c['Border'], SOLID);
  sh.getRange(R0, 2, N, 1).setFontColor(c['Input Text']).setFontFamily('Share Tech Mono')
    .setFontWeight('bold').setHorizontalAlignment('center');
  sh.getRange(R0, 4, N, 1).setFontFamily('Share Tech Mono').setHorizontalAlignment('center');
  sh.getRange(R0, 6, N, 1).setFontColor(c['Text Dim']).setFontStyle('italic');
  [3, 5].forEach(col => sh.getRange(R0, col, N, 1)
    .setBorder(true, true, true, true, null, true, c['Border'], SOLID));

  // Notes
  sh.getRange(ED.NOTES_ROW, 1).setFontFamily(t.titleFont).setFontColor(c['Title'])
    .setFontWeight('bold').setFontSize(10);
  sh.getRange(ED.NOTES_ROW + 1, 1, ED.NOTES_LINES, 1).setFontColor(c['Text Dim']);
}

// ------------------------------------------------------------------ Themes tab

function styleThemes_(sh, t) {
  const c = t.c;
  sh.setHiddenGridlines(true);
  const lastR = sh.getLastRow(), lastC = sh.getLastColumn();
  if (lastR < 2 || lastC < 2) return;
  sh.getRange(1, 1, 1, lastC).setBackground(c['Accent'])
    .setFontColor(c['Accent Text']).setFontWeight('bold');
  const vals = sh.getRange(2, 2, lastR - 1, lastC - 1).getDisplayValues();
  const bgs = vals.map(row => row.map(v => HEX.test(v.trim()) ? v.trim() : c['Background']));
  const fgs = bgs.map(row => row.map(contrast_));
  sh.getRange(2, 2, lastR - 1, lastC - 1).setBackgrounds(bgs).setFontColors(fgs);
  sh.getRange(2, 1, lastR - 1, 1).setBackground(c['Panel']).setFontColor(c['Text']);
}

// ── Upgrade.gs ────────────────────────────────────────────────────────────

/**
 * EDLD sheet — the sheet's own upgrade steps.
 *
 * Bundled with Code.gs and Dashboard.gs into edld_sheet.js. Loader.gs installs
 * a new bundle and then calls upgradeSheet() from it, so the steps that run
 * are always the ones that shipped with the code they prepare the sheet for.
 *
 * The sheet's layout version is kept in its document properties as
 * EDLD_SHEET_VERSION. A sheet from before there was a version — anything set
 * up by pasting Code.gs, with or without the dashboard template — has none,
 * and is version 0. Each entry in SHEET_MIGRATIONS brings a sheet to its `to`
 * version; upgradeSheet() runs every entry above the sheet's version, in
 * order, and records each as it completes, so an interrupted upgrade resumes
 * where it stopped.
 *
 * Rules for a step:
 *   - Safe to run twice. It is re-run if the one after it fails.
 *   - Deposits is only ever added to. No column is moved or removed, because
 *     every EDLD writing to the sheet addresses columns by position.
 *   - Settings values are the owner's. A step may add a row, never rewrite one.
 *   - Tabs a sheet does not have are skipped, not created. A receiver-only
 *     sheet upgrades its Deposits and nothing else.
 *
 * Append new steps; never edit one that has shipped.
 */

var SHEET_VERSION_PROPERTY = 'EDLD_SHEET_VERSION';

/** Oldest Loader.gs this bundle can run under. Raised only when it must be. */
var MIN_LOADER = 1;

var SHEET_MIGRATIONS = [
  {
    to: 1,
    name: 'Notes and assessment columns; Notes on the dashboard; depletion as a date',
    run: function (ss) {
      _sheet();                 // Code.gs: widens the Deposits header in place
      tidyDeposits_(ss);
      if (rebuildDashboard_(ss)) applyTheme();
    }
  }
];

/** The layout version the steps above bring a sheet to. */
var SHEET_VERSION = SHEET_MIGRATIONS[SHEET_MIGRATIONS.length - 1].to;

function sheetVersion_() {
  return Number(PropertiesService.getDocumentProperties()
                  .getProperty(SHEET_VERSION_PROPERTY) || 0);
}

/**
 * Bring the sheet to SHEET_VERSION. Returns what was done, for the loader to
 * report. Backs up Deposits first whenever there is anything to do.
 */
function upgradeSheet() {
  var ss = SpreadsheetApp.getActive();
  var doc = PropertiesService.getDocumentProperties();
  var have = sheetVersion_();
  var todo = SHEET_MIGRATIONS.filter(function (m) { return m.to > have; });
  var result = { from: have, to: have, steps: [], backup: '' };
  if (!todo.length) return result;

  result.backup = backupDeposits_(ss);
  for (var i = 0; i < todo.length; i++) {
    todo[i].run(ss);
    doc.setProperty(SHEET_VERSION_PROPERTY, String(todo[i].to));
    result.to = todo[i].to;
    result.steps.push(todo[i].name);
  }
  return result;
}

/**
 * A hidden copy of Deposits, named for when it was taken. Nothing is deleted:
 * a backup is only worth having if it is still there when somebody notices
 * they need it, and they can remove old ones themselves. Returns its name,
 * or '' when there were no rows to protect.
 */
function backupDeposits_(ss) {
  var deps = ss.getSheetByName(SHEET_NAME);
  if (!deps || deps.getLastRow() < 2) return '';
  var stamp = Utilities.formatDate(new Date(), Session.getScriptTimeZone(),
                                   'yyyy-MM-dd HHmm');
  var name = SHEET_NAME + ' backup ' + stamp;
  var n = 2;
  while (ss.getSheetByName(name)) name = SHEET_NAME + ' backup ' + stamp + ' (' + (n++) + ')';
  var copy = deps.copyTo(ss);
  copy.setName(name);
  copy.hideSheet();
  return name;
}

/**
 * Deposits as the current rules expect them, without changing what any row
 * says. "Depleted" leaves the amount column — depletion is the date alone —
 * and a depletion date Sheets parsed into a date becomes the plain day it was
 * sent as, so the table and a fetch agree on which day it was.
 */
function tidyDeposits_(ss) {
  var deps = ss.getSheetByName(SHEET_NAME);
  if (!deps || deps.getLastRow() < 2) return;
  var head = deps.getRange(1, 1, 1, deps.getLastColumn()).getValues()[0];
  var rows = deps.getLastRow() - 1;

  var amount = head.indexOf('amount') + 1;
  if (amount > 0) {
    var ar = deps.getRange(2, amount, rows, 1);
    var av = ar.getValues();
    if (av.some(function (v) { return v[0] === 'Depleted'; })) {
      ar.setValues(av.map(function (v) { return [v[0] === 'Depleted' ? '' : v[0]]; }));
    }
  }

  var depleted = head.indexOf('depleted_on') + 1;
  if (depleted > 0) {
    var dr = deps.getRange(2, depleted, rows, 1);
    var dv = dr.getValues();
    var isDate = function (v) {
      return Object.prototype.toString.call(v) === '[object Date]';
    };
    if (dv.some(function (v) { return isDate(v[0]); })) {
      // Every cell is written back as text, not only the converted ones: a
      // day already stored as text would otherwise be parsed on the way in.
      dr.setValues(dv.map(function (v) {
        return [v[0] === '' || v[0] === null ? '' : "'" + _day(v[0])];
      }));
    }
  }
}

return {
  version: EDLD_VERSION,
  doPost: doPost,
  doGet: doGet,
  onEdit: onEdit,
  onSelectionChange: onSelectionChange,
  MENU: MENU,
  upgradeSheet: upgradeSheet,
  sheetVersion: sheetVersion_,
  SHEET_VERSION: SHEET_VERSION,
  MIN_LOADER: MIN_LOADER
};
